### PR TITLE
Simple multiplatform compile commands

### PR DESCRIPTION
**Pull request by CodeMaxx**
Fix for #91 and #86 

@Ali-Razmjoo @jowasp

### CODE REVIEW

**Comment by CodeMaxx** [comment]
@Pratik151 I hope this works for Windows as well

**Comment by Ali-Razmjoo** [comment]
I think we need to split windows , osx& linux, and by the way, this command is just for 32bit, we could add multi line examples.

```
windows: gcc file.c -o file.exe ---> it works fine
```

and i think linux needs `-z execstack` I've to test it.

**Comment by CodeMaxx** [comment]
Updated

**Comment by Ali-Razmjoo** [comment]
thanks.

**Pull request merged**
