### PR TITLE
pep8 fixes

### PR DESCRIPTION
**Pull request by CodeMaxx**
Code formatting is absolutely necessary for large project like ours to keep common formatting standards for all developers and also improve readability of the code. Thus I formatted the code according to `pep8` rules using google's [yapf](https://github.com/google/yapf) python formatter using the default settings.

Any discussions regarding using a different formatter or having some personal settings for yapf are welcome. 

@Ali-Razmjoo @Pratik151 @jowasp

### CODE REVIEW

**Comment by Pratik151** [comment]
I think this will change most of the code so its good if its done by Ali. What do you say?

**Comment by Ali-Razmjoo** [comment]
It takes much time to review the codes, but i'll try.

**Comment by CodeMaxx** [comment]
@Pratik151 This software does not change the code, it just reformats it....you know like keeping proper amount of indentation etc. So I mean the logic and syntax will remain the same.

@Ali-Razmjoo I've been using this software since 6 months for all my python project and have never had any errors on reformatting. Also `yapf` has a `--verify` flag to check for syntax error after reformatting. I used this flag but it gave no errors. We did this in [symengine](https://github.com/symengine/symengine)(Another open source project I used to work on) as well.So I think all should be fine.  If you still want to be very sure then you'll have to review all the code.

**Comment by CodeMaxx** [comment]
@Ali-Razmjoo Merge conflicts fixed

**Comment by CodeMaxx** [comment]
@Ali-Razmjoo Can you block other PRs until this is merged? Otherwise merge conflicts would have to be corrected again and again. I hope you understand.

**Comment by Ali-Razmjoo** [comment]
thanks, merged

**Pull request merged**
